using System;

namespace Arithmetic
{
    class Program
    {
        static void Main(string[] args)
        {
            int a
            int b 
        
                a = Console.Read();
                b = Console.Read();
            int add = a + b;
            int sb = a-b;
            int mult = a * b;
            int div = a/b;
            
            if(add == mult )
            {
            Console.WriteLine("True");
            }
            else 
            {
             Console.WriteLine("false");
             }
             else if(div == sb)
             {
              Console.WriteLine("True");
              }
              else
              {
               Console.WriteLine("false");
               
      

                  }
    }
}






